# Generated by Django 6.0 on 2026-01-02 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('pilates', 'Pilates'), ('academia', 'Academia'), ('fisioterapia', 'Fisioterapia'), ('massagem', 'Massagem'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Serviços',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='servicos.servico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
