# Generated by Django 6.0 on 2026-01-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_servico_paciente_servico_paciente_valor_mensalidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
