# Generated by Django 6.0 on 2026-01-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_delete_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dia_vencimento',
            field=models.IntegerField(blank=True, help_text='Dia do mês para vencimento da mensalidade (1-31)', null=True, verbose_name='Dia de Vencimento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='inicio_atividades',
            field=models.DateField(blank=True, help_text='Data em que o paciente começou a utilizar a clínica', null=True, verbose_name='Início das Atividades'),
        ),
    ]
