# Generated by Django 6.0 on 2026-01-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('parcial', 'Parcialmente Paga'), ('vencida', 'Vencida')], default='pendente', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='pacientes.paciente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.servico')),
            ],
            options={
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['data_vencimento'],
                'indexes': [models.Index(fields=['paciente', 'status'], name='mensalidade_pacient_644019_idx'), models.Index(fields=['data_vencimento', 'status'], name='mensalidade_data_ve_fe186a_idx')],
            },
        ),
    ]
