# Generated by Django 6.0 on 2026-01-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('pilates', 'Pilates'), ('academia', 'Academia'), ('fisioterapia', 'Fisioterapia'), ('massagem', 'Massagem'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Serviços',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
