# Generated by Django 6.0 on 2026-01-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('credito', 'Cartão Crédito'), ('debito', 'Cartão Débito'), ('transferencia', 'Transferência'), ('cheque', 'Cheque'), ('pix', 'PIX')], max_length=20)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('numero_recibo', models.CharField(blank=True, max_length=50, unique=True)),
                ('observacoes', models.TextField(blank=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='mensalidades.mensalidade')),
            ],
            options={
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
                'indexes': [models.Index(fields=['data_pagamento'], name='caixa_pagam_data_pa_2db016_idx'), models.Index(fields=['metodo_pagamento'], name='caixa_pagam_metodo__c2c259_idx')],
            },
        ),
    ]
