# Generated by Django 6.0 on 2026-01-03 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
        ('pacientes', '0003_delete_servico'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('categoria_entrada', models.CharField(blank=True, choices=[('mensalidade', 'Mensalidade'), ('sessao_avulsa', 'Sessão Avulsa'), ('outro', 'Outro')], max_length=20, null=True)),
                ('categoria_saida', models.CharField(blank=True, choices=[('despesa', 'Despesa'), ('aluguel', 'Aluguel'), ('funcionario', 'Funcionário'), ('outro', 'Outro')], max_length=20, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observacoes', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_caixa', to='pacientes.paciente')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.servico')),
            ],
            options={
                'verbose_name_plural': 'Movimentações de Caixa',
                'ordering': ['-data_movimentacao'],
                'indexes': [models.Index(fields=['data_movimentacao', 'tipo'], name='caixa_movim_data_mo_2e8873_idx')],
            },
        ),
    ]
