# Generated by Django 6.0 on 2026-01-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_movimentacaocaixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaocaixa',
            name='servico',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
