# Generated by Django 6.0 on 2026-01-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_remove_movimentacaocaixa_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AberturaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_entradas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_saidas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aberto', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Abertura de Caixa',
                'verbose_name_plural': 'Aberturas de Caixa',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
