# Generated by Django 6.0 on 2026-01-31 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0006_sync_caixa_fields'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaocaixa',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('cheque', 'Cheque'), ('outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaocaixa',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_caixa', to='servicos.servico'),
        ),
    ]
